export const serviceItems = [
  {
    id: "house-cleaning",
    title: "House Cleaning",
    description: "Professional residential cleaning services to keep your home spotless, healthy, and welcoming for you and your family.",
    fullDescription: "Our house cleaning service is designed to take the burden of household chores off your shoulders. We provide comprehensive cleaning that covers everything from dusting and vacuuming to sanitizing kitchens and bathrooms. Whether you need a weekly touch-up or a one-time deep clean, our professional team ensures your living space is pristine and healthy.",
    features: [
      "Dusting and wiping all surfaces",
      "Vacuuming and mopping floors",
      "Kitchen appliance cleaning",
      "Bathroom sanitization and scrubbing",
    ],
    benefits: [
      "Save time and energy for what matters most.",
      "Professional-grade cleaning products and equipment.",
      "Customizable cleaning plans tailored to your home.",
      "Consistent, high-quality results every visit.",
    ],
    process: [
      { title: "Consultation", description: "We discuss your specific needs and create a customized cleaning plan for your home." },
      { title: "Systematic Clean", description: "Our trained staff follows a detailed checklist to ensure every corner is touched." },
      { title: "Quality Check", description: "A supervisor reviews the work to maintain our high standards of excellence." },
      { title: "Final Walkthrough", description: "We ensure you are 100% satisfied with the results before we leave." },
    ],
    faqs: [
      { question: "Do I need to be home during the cleaning?", answer: "No, most of our clients provide us with a key or access code. We are fully insured and bonded for your peace of mind." },
      { question: "Do you provide cleaning supplies?", answer: "Yes, we bring all necessary professional-grade equipment and eco-friendly cleaning solutions." },
      { question: "Is your staff background-checked?", answer: "Absolutely. Every member of our team undergoes a rigorous background check and professional training." },
    ],
    image: {
      src: "/images/house -cleaning.webp",
      alt: "House Cleaning",
      width: 835,
      height: 539,
    },
  },
  {
    id: "hospital-cleaning",
    title: "Hospital Cleaning",
    description: "High-standard medical facility sanitization ensuring a sterile and safe environment for patients and healthcare professionals.",
    fullDescription: "In medical environments, cleanliness is a matter of safety. Our hospital cleaning services adhere to strict healthcare standards to prevent cross-contamination and ensure a sterile environment. We use medical-grade disinfectants and follow rigorous protocols for clinics, hospitals, and dental offices.",
    features: [
      "Operating room and sterile zone cleaning",
      "Patient room disinfection",
      "Waiting area and high-traffic sanitization",
      "Biohazard waste handling support",
    ],
    benefits: [
      "Compliance with healthcare safety regulations.",
      "Reduced risk of healthcare-associated infections (HAIs).",
      "Peace of mind for patients and medical staff.",
      "Specialized training for medical facility protocols.",
    ],
    process: [
      { title: "Risk Assessment", description: "We evaluate the specific requirements of different zones (sterile, public, administrative)." },
      { title: "Deep Sanitization", description: "Application of medical-grade disinfectants following strict contact-time protocols." },
      { title: "Validation", description: "Testing and inspection to ensure all microbial standards are met." },
      { title: "Ongoing Monitoring", description: "Regular audits and reporting to maintain continuous compliance." },
    ],
    faqs: [
      { question: "Do you follow CDC/WHO guidelines?", answer: "Yes, we strictly adhere to the latest healthcare cleaning protocols from international health organizations." },
      { question: "Are your cleaners trained for medical environments?", answer: "Yes, our hospitality cleaners undergo specialized training for sanitization in healthcare settings." },
    ],
    image: {
      src: "/images/hospital-cleaning.jpg",
      alt: "Hospital Cleaning",
      width: 1052,
      height: 648,
    },
  },
  {
    id: "office-cleaning",
    title: "Office Cleaning",
    description: "Daily and periodic office maintenance to create a productive, professional, and hygienic workspace for your team.",
    fullDescription: "A clean office is a productive office. Our team provides discreet and thorough cleaning services for corporate environments, focusing on desk areas, conference rooms, and communal kitchens. We work around your schedule—whether after hours or during the day—to maintain a professional atmosphere.",
    features: [
      "Workstation and desk sanitization",
      "Conference room and lobby maintenance",
      "Trash removal and recycling management",
      "Kitchenette and restroom cleaning",
    ],
    benefits: [
      "Enhanced employee productivity and morale.",
      "Professional impression for clients and visitors.",
      "Healthy workspace reducing sick leaves.",
      "Flexible scheduling to avoid business disruption.",
    ],
    process: [
      { title: "Site Survey", description: "We walk through your office to identify high-traffic areas and specific needs." },
      { title: "Off-Hours Cleaning", description: "Our team performs thorough cleaning when it least disrupts your business operations." },
      { title: "Daily Maintenance", description: "Ongoing support to keep communal areas and restrooms pristine throughout the day." },
    ],
    faqs: [
      { question: "Can you clean during office hours?", answer: "Yes, we offer both day-time porter services and after-hours deep cleaning." },
      { question: "Do you provide green cleaning options?", answer: "Yes, we use eco-friendly products that are safe for your employees and the environment." },
    ],
    image: {
      src: "/images/office-cleaning.jpg",
      alt: "Office Cleaning",
      width: 1050,
      height: 648,
    },
  },
  {
    id: "building-cleaning",
    title: "Building Cleaning",
    description: "Comprehensive exterior and interior maintenance for commercial and residential buildings to preserve property value.",
    fullDescription: "We provide full-scale building maintenance services for residential complexes and commercial towers. From lobby management to exterior power washing, our team ensures every inch of your property is well-maintained and visually appealing.",
    features: [
      "Common area and hallway maintenance",
      "Lobby and entrance cleaning",
      "Exterior pressure washing",
      "Floor waxing and polishing",
    ],
    benefits: [
      "Improved property value and longevity.",
      "Enhanced curb appeal for residents and tenants.",
      "Proactive maintenance catching minor issues early.",
      "Safe and clean environment for all building users.",
    ],
    process: [
      { title: "Lobby & Entry", description: "First impressions matter; we ensure your building entrance is always spotless." },
      { title: "Floor-by-Floor", description: "Systematic maintenance of hallways, stairs, and common amenities." },
      { title: "Exterior Care", description: "Periodic pressure washing and window cleaning to maintain the building's facade." },
    ],
    faqs: [
      { question: "Do you offer seasonal maintenance?", answer: "Yes, we have specialized plans for window cleaning and exterior care during different seasons." },
    ],
    image: {
      src: "/images/building-cleaning.jpg",
      alt: "Building Cleaning",
      width: 832,
      height: 536,
    },
  },
  {
    id: "window-cleaning",
    title: "Window Cleaning",
    description: "Crystal clear window cleaning for high-rise buildings and residential homes using professional-grade equipment.",
    fullDescription: "Our window cleaning services provide streak-free results for any type of building. We use specialized squeegees, extension poles, and water-fed systems to reach difficult spots safely, ensuring your view is never obstructed by dirt or grime.",
    features: [
      "Interior and exterior glass cleaning",
      "Sill and frame wiping",
      "Screen cleaning and debris removal",
      "High-reach safety equipment usage",
    ],
    benefits: [
      "Increased natural light and better views.",
      "Removal of corrosive contaminants on glass.",
      "Professional finish without water spots.",
      "Safe handling of high-rise and difficult windows.",
    ],
    process: [
      { title: "Safety Setup", description: "We secure the area and deploy appropriate reach equipment for safe operation." },
      { title: "Glass Washing", description: "Multi-step washing process to remove salt, dirt, and mineral buildup." },
      { title: "Detailing", description: "Wiping of edges and frames for a perfectly clear, streak-free finish." },
    ],
    faqs: [
      { question: "How often should windows be cleaned?", answer: "We recommend professional cleaning at least twice a year to prevent glass degradation." },
    ],
    image: {
      src: "/images/Window-Cleaning.webp",
      alt: "Window Cleaning",
      width: 736,
      height: 502,
    },
  },
  {
    id: "carpet-cleaning",
    title: "Carpet Cleaning",
    description: "Deep steam cleaning and stain removal to restore the look and feel of your carpets and upholstery.",
    fullDescription: "Carpets trap dust, allergens, and odors over time. Our deep cleaning process uses industrial-grade steam cleaners and eco-friendly solutions to lift stains and refresh fibers, extending the life of your flooring and improving indoor air quality.",
    features: [
      "Pre-treatment for heavy stains",
      "Hot water extraction (steam cleaning)",
      "Deodorizing and sanitizing",
      "Upholstery and rug care",
    ],
    benefits: [
      "Removal of deep-seated dirt and allergens.",
      "Elimination of tough stains and odors.",
      "Restoration of carpet texture and appearance.",
      "Improved indoor air quality for residents.",
    ],
    process: [
      { title: "Fiber Analysis", description: "We identify the carpet material to choose the most effective and safe cleaning method." },
      { title: "Stain Pre-treatment", description: "Targeted application of non-toxic solutions to lift difficult spots." },
      { title: "Extraction", description: "Powerful steam extraction to remove dirt from the base of the fibers." },
    ],
    faqs: [
      { question: "How long does the carpet take to dry?", answer: "Typically between 4 to 8 hours depending on humidity and airflow." },
    ],
    image: {
      src: "/images/carpet-cleaning.jpg",
      alt: "Carpet Cleaning",
      width: 835,
      height: 539,
    },
  },
  {
    id: "deep-cleaning",
    title: "Deep Cleaning",
    description: "Intensive cleaning for every corner of your space, removing built-up grime and ensuring total hygiene.",
    fullDescription: "When standard cleaning isn't enough, our deep cleaning service provides a top-to-bottom overhaul. We focus on 'hidden' areas like behind appliances, inside cabinets, and high-level surfaces to ensure your space is truly sanitized.",
    features: [
      "Behind and under appliance cleaning",
      "Wall and ceiling dusting",
      "Intensive grout and tile scrubbing",
      "Cabinet and drawer interior cleaning",
    ],
    benefits: [
      "Perfect for move-in/move-out situations.",
      "Total elimination of hidden grime and dust.",
      "Foundation for easier routine maintenance.",
      "Highest level of sanitization possible.",
    ],
    process: [
      { title: "Top-to-Bottom", description: "We start from the ceiling and work down to ensure no dust is resettled." },
      { title: "Deep Sanitization", description: "Focusing on kitchens, bathrooms, and high-touch areas with intensive scrubbing." },
      { title: "Final Polish", description: "Every surface is polished to a shine, leaving the home looking like new." },
    ],
    faqs: [
      { question: "Is this recommended for move-ins?", answer: "Yes, it is the best way to ensure your new home is clean and sanitized before you unpack." },
    ],
    image: {
      src: "/images/Deep-Cleaning.jpg",
      alt: "Deep Cleaning",
      width: 832,
      height: 536,
    },
  },
  {
    id: "banquet",
    title: "Banquet",
    description: "Full-service banquet management and setup for weddings, corporate events, and special celebrations.",
    fullDescription: "Host your event with confidence. Our banquet services include everything from initial floor planning and table setup to coordinated service during the meal. We work closely with event planners to ensure every detail matches your vision.",
    features: [
      "Table and chair arrangement",
      "Linen and decor coordination",
      "Coordinated meal service timing",
      "Post-event breakdown and cleanup",
    ],
    benefits: [
      "Stress-free hosting for the organizers.",
      "Seamless and professional guest experience.",
      "Attention to detail in decor and service.",
      "Scalable staff for events of any size.",
    ],
    process: [
      { title: "Event Briefing", description: "Our team reviews the schedule and service flow with the event organizers." },
      { title: "Venue Setup", description: "Precise arrangement of tables, chairs, and decor as per the floor plan." },
      { title: "Live Service", description: "Professional management of the meal and guest needs throughout the event." },
    ],
    faqs: [
      { question: "Do you provide decor?", answer: "We focus on service and setup, but we can coordinate with your decor partners." },
    ],
    image: {
      src: "/images/banqeat-cleaning.jpg",
      alt: "Banquet",
      width: 835,
      height: 539,
    },
  },
  {
    id: "housekeeping",
    title: "Housekeeping",
    description: "Dedicated housekeeping services for hotels, apartments, and private residences to maintain order and cleanliness.",
    fullDescription: "Our housekeeping services focus on the daily maintenance of hospitality environments and luxury residences. We handle bed making, laundry, and general organization to ensure a consistently comfortable and tidy environment for guests or owners.",
    features: [
      "Bed making and linen changing",
      "Laundry and ironing services",
      "General organizing and tidying",
      "Room-by-room thorough maintenance",
    ],
    benefits: [
      "Consistently tidy and organized living spaces.",
      "Hotel-quality room presentation.",
      "Reduced workload for homeowners or hotel staff.",
      "Professional and discreet service.",
    ],
    process: [
      { title: "Morning Routine", description: "Systematic room tidying, bed making, and laundry collection." },
      { title: "Detailing", description: "Bathroom sanitization and surface polishing to maintain a 'fresh' feel." },
      { title: "Turn-down Service", description: "Evening preparation to ensure maximum comfort for the night." },
    ],
    faqs: [
      { question: "Is your staff trained for luxury hotels?", answer: "Yes, our team follows international 5-star housekeeping standards." },
    ],
    image: {
      src: "/images/housekeeping service.jpg",
      alt: "Housekeeping",
      width: 835,
      height: 539,
    },
  },
  {
    id: "outside-catering",
    title: "Outside Catering",
    description: "Premium catering services delivered to your venue, featuring diverse menus tailored to your event's needs.",
    fullDescription: "Bring professional culinary experiences to any location. Our outside catering team handles transport, setup, and service at your chosen venue, providing delicious menus that can range from casual buffets to formal multi-course dinners.",
    features: [
      "Customizable menu planning",
      "Safe food transport and holding",
      "On-site kitchen setup (if required)",
      "Buffet or plated service options",
    ],
    benefits: [
      "Gourmet food at the location of your choice.",
      "Professional presentation and service staff.",
      "Flexible catering for various group sizes.",
      "Focus on food safety and quality.",
    ],
    process: [
      { title: "Menu Tasting", description: "We help you select the perfect dishes with a pre-event tasting session." },
      { title: "On-Site Setup", description: "Safe transport and professional presentation of food at your venue." },
      { title: "Managed Service", description: "Our chefs and waiters ensure every guest is served perfectly." },
    ],
    faqs: [
      { question: "Do you handle dietary restrictions?", answer: "Yes, we can accommodate vegan, gluten-free, and various allergy requirements." },
    ],
    image: {
      src: "/images/outside-catering.jpg",
      alt: "Outside Catering",
      width: 835,
      height: 539,
    },
  },
  {
    id: "waiter-waitress",
    title: "Waiter & Waitress",
    description: "Professional and courteous service staff for events, restaurants, and private functions.",
    fullDescription: "Our service staff are trained in formal dining etiquette and efficient hospitality service. Whether you need additional help for a busy restaurant night or dedicated servers for a private dinner, our team provides friendly and professional guest care.",
    features: [
      "Order taking and food delivery",
      "Table clearing and resetting",
      "Beverage service and pouring",
      "Guest inquiry handling",
    ],
    benefits: [
      "Professional and polite guest interaction.",
      "Efficient and timely food and drink service.",
      "Uniformed staff reflecting your brand's quality.",
      "Experienced in various service styles (French, Russian, Buffet).",
    ],
    process: [
      { title: "Role Briefing", description: "Our staff is briefed on the menu, guest list, and specific service style." },
      { title: "Guest Care", description: "Attentive service throughout the event, focusing on guest comfort." },
      { title: "Station Management", description: "Ensuring tables are cleared and guests have everything they need." },
    ],
    faqs: [
      { question: "Are your staff uniformed?", answer: "Yes, we provide professionally uniformed staff to match your event's theme." },
    ],
    image: {
      src: "/images/waiter-service.jpeg",
      alt: "Waiter & Waitress",
      width: 1052,
      height: 648,
    },
  },
  {
    id: "hospitality-cleaner",
    title: "Hospitality Cleaner",
    description: "Specialized cleaners for the hospitality sector, focusing on guest experience and high-traffic area maintenance.",
    fullDescription: "Hospitality cleaning requires a balance of thoroughness and discretion. Our team is trained to clean hotel lobbies, gyms, and restaurants during operational hours while maintaining a polite presence and ensuring guest areas are always inviting.",
    features: [
      "Lobby and reception area polishing",
      "Public restroom frequency cleaning",
      "Elevator and touchpoint sanitization",
      "Back-of-house hygiene maintenance",
    ],
    benefits: [
      "Enhanced guest perception of quality.",
      "Discreet cleaning that doesn't disrupt guests.",
      "Focus on high-visibility touchpoints.",
      "Support for existing housekeeping teams.",
    ],
    process: [
      { title: "High-Traffic Scan", description: "Continuous monitoring and cleaning of elevators, entryways, and restrooms." },
      { title: "Guest Area Care", description: "Polishing surfaces and maintaining public spaces with minimal disruption." },
    ],
    faqs: [
      { question: "How do you handle day-time cleaning?", answer: "Our staff is trained to be discreet and respectful of guests at all times." },
    ],
    image: {
      src: "/images/hospitality -cleaner.jpg",
      alt: "Hospitality Cleaner",
      width: 1050,
      height: 648,
    },
  },
  {
    id: "general-chef-services",
    title: "General Chef Services",
    description: "Expert culinary services for private homes, corporate offices, and event catering.",
    fullDescription: "Our chefs bring restaurant-quality cooking to your kitchen. From meal prepping for families to designing menus for corporate executives, we provide professional culinary expertise tailored to your dietary preferences and tastes.",
    features: [
      "Menu design and ingredient sourcing",
      "On-site food preparation and cooking",
      "Kitchen management and sanitation",
      "Special dietary (Vegan, Keto, GF) accommodation",
    ],
    benefits: [
      "Restaurant-quality meals in a private setting.",
      "Tailored menus to your exact tastes.",
      "Professional handling of kitchen and food safety.",
      "Save time on meal planning and preparation.",
    ],
    process: [
      { title: "Menu Creation", description: "Personal consultation to design a menu that fits your taste and nutrition goals." },
      { title: "Ingredient Sourcing", description: "We select the freshest, highest-quality local ingredients." },
      { title: "Culinary Execution", description: "Professional cooking and plating in your home or office kitchen." },
    ],
    faqs: [
      { question: "Can you provide daily meal prep?", answer: "Yes, we offer both one-time event chef services and ongoing meal preparation." },
    ],
    image: {
      src: "/images/General Chef Services.jpg",
      alt: "General Chef Services",
      width: 832,
      height: 536,
    },
  },
  {
    id: "office-tea-boy",
    title: "Office Tea Boy",
    description: "Reliable pantry and office support staff to handle beverage service and light administrative tasks.",
    fullDescription: "Maintain a hospitable office environment with our pantry support staff. Our 'tea boys' are trained in beverage preparation, guest greeting, and basic office support, ensuring your team and visitors are always well-cared for.",
    features: [
      "Beverage preparation (tea, coffee, etc.)",
      "Pantry and kitchen area maintenance",
      "Guest greeting and refreshments",
      "Light office support (photocopying, errands)",
    ],
    benefits: [
      "Professional and hospitable office atmosphere.",
      "Staff freed up for more complex tasks.",
      "Consistent availability of refreshments for guests.",
      "Tidy and hygienic office pantry areas.",
    ],
    process: [
      { title: "Morning Prep", description: "Setting up the pantry and preparing the first round of morning refreshments." },
      { title: "Ongoing Support", description: "Attentive beverage service and pantry tidying throughout the workday." },
    ],
    faqs: [
      { question: "Is training provided?", answer: "Yes, all our pantry staff are trained in hospitality and basic office etiquette." },
    ],
    image: {
      src: "/images/Office Tea Boy.jpg",
      alt: "Office Tea Boy",
      width: 736,
      height: 502,
    },
  },
  {
    id: "assistant-bartender",
    title: "Assistant Bartender",
    description: "Skilled support for beverage services, ensuring smooth operations at bars and event lounges.",
    fullDescription: "Our bar assistants (barbacks) ensure that your main bartenders can focus on making drinks. They handle glass washing, garnish preparation, and stock replenishment, keeping the bar area clean and efficient during peak hours.",
    features: [
      "Glassware washing and polishing",
      "Ingredient and ice replenishment",
      "Garnish preparation and cutting",
      "Bar counter and floor maintenance",
    ],
    benefits: [
      "Faster drink service for guests.",
      "Clean and organized bar environment.",
      "Support for lead bartenders during rushes.",
      "Reduced downtime for stock runs.",
    ],
    process: [
      { title: "Bar Setup", description: "Preparing the bar with ice, clean glassware, and fresh garnishes before service." },
      { title: "Live Support", description: "Behind-the-scenes work to keep the bar running smoothly during high-volume periods." },
    ],
    faqs: [
      { question: "Do they handle money?", answer: "Typically no, their role is focused on operational support for the lead bartender." },
    ],
    image: {
      src: "/images/Assistant Bartender.webp",
      alt: "Assistant Bartender",
      width: 835,
      height: 539,
    },
  },
  {
    id: "steward",
    title: "Steward",
    description: "Professional stewards for marine, aviation, or high-end hospitality environments.",
    fullDescription: "Our stewards provide high-end guest care in specialized environments. Trained in luxury service standards, they handle cabin maintenance, luggage care, and refined table service, ensuring a premium experience for every guest.",
    features: [
      "Luxury cabin or room maintenance",
      "Luggage and personal care support",
      "Fine dining service assistance",
      "Guest comfort and needs management",
    ],
    benefits: [
      "Premium, high-end guest experience.",
      "Refined and professional service standards.",
      "Attention to detail in guest comfort.",
      "Experience in specialized environments (Yachts, Private Jets).",
    ],
    process: [
      { title: "Guest Orientation", description: "Welcoming guests and ensuring they are familiar with all amenities and services." },
      { title: "Dedicated Care", description: "Anticipating and fulfilling guest needs with professional discretion." },
    ],
    faqs: [
      { question: "What environments do you support?", answer: "We provide stewards for luxury residential complexes, private aviation, and yachts." },
    ],
    image: {
      src: "/images/Steward.jpg",
      alt: "Steward",
      width: 832,
      height: 536,
    },
  },
];
